### ISSUE TITLE
Raycast

### ISSUE THREAD

**Issue by BigMo** [rohvani/CSGOBot#2]
Hey dude!

Would you mind spending a moment or two and help me implementing that raycast?
I took some if your code to parse the BSP and it works quite well. Displaying it is no problem either.
I just can't figure out how to successfully make a raycast. I did the following (pseudo-code):
directionVector = targetPlayer.Vector - localPlayer.Vector
Raycast(localPlayer.Vector, directionVector...)
But it screws up - There is a hit every time with fraction ranging from 1 to 2.
It seems you didn't implement visibility-checking at all, did you?

**Comment by rohvani** [comment]
I didn't!  For some reason I wasn't able to load the proper faces of the BSP into the Jitter world, thus never being able to complete the visibility aspect.  

If you've managed to fix that, make sure you're only loading surfaces that have a texture without the SURF_NODRAW flag (https://developer.valvesoftware.com/wiki/Source_BSP_File_Format#Texinfo), there might be better ways to determine whether a face is included in the physics data.  One alternative is to look at BSP's physics data (like lump 29 [LUMP_PHYSCOLLIDE] and 49 [LUMP_PHYSCOLLIDESURFACE]).

Let me know how it goes!  Feel free to submit pull requests.

**Comment by BigMo** [comment]
To ensure that I read data correctly, I display the world around each
player within a certain radius (which btw looks really nice) and it seems
to work fine. As you said, I'll implement checking for invalid vertices
that are part of buyzones and stuff - I think of reading brush.contents and
check for CONTENTS_SOLID ;).
I'll make a pull request once I completely implemented it and got this damn
raycast working!

2015-01-11 1:14 GMT+01:00 Seefo notifications@github.com:
