### ISSUE TITLE
can open

### ISSUE THREAD

**Issue by Fr0zenSpy** [rohvani/CSGOBot#3]
so i can't open it with visual studio 2017  it told me to download monogame are something like that i did that tryed again and still not working :(

**Comment by rohvani** [comment]
I think I used visual studio 12 for this, but either way, I don't recommend using this project in any sense other than for reference.  The memory addresses used are very unorthodox, and the code is spaghetti.  Any attempt to use this project in any serious capacity will be a waste of time, and require a large rewrite.
